server:
  port: 8076

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/certs
#          issuer-uri: http://localhost:8080
#          issuer-uri: https://connect.test.surfconext.nl/oidc/.well-known/openid-configuration


